// Real product images from local images folder
export const realProductImages = [
    '../images/Mini Combo.png',
    '../images/DH_Weight1.png',
    '../images/CURVE_OIL.png',
    '../images/DH_CURVES.png',
    '../images/COMBO_MAX.png',
    '../images/Big_Butt.png',
    '../images/Milk.jpg',
];

export const productsData = {
    'mini-combo-set': {
        id: 'mini-combo-set',
        name: 'Mini Combo Set',
        brand: 'DHERBALBODY SKINCARE',
        category: 'BODY CREAM',
        price: 95.00,
        originalPrice: null,
        rating: 4.8,
        reviewCount: 156,
        images: [realProductImages[0], '../images/additional_images/Combo-Max2.jpg'],
        inStock: true,
        isNew: false,
        onSale: false,
        isBestSeller: true,
        variants: ['#98fb98', '#90ee90'],
        skinType: ['fair', 'light'],
        unitCount: ['50ml'],
        features: ['Natural organic ingredients', 'Deep moisturizing formula'],
        description: '(Mini Combo Set) This is a combination of both the "Big Butt Formula" Cream & The "Bum curve essential Oils". This combo gives you an extra edge in enhancing & beautifying those sides. All naturally hand made products. We have made Combo\'s more affordable when put together than buying separately too. It\'s a win! win!! For External Use Only. Price $95',
        ingredients: 'Aqua, Citrus Extract, Glycerin, Shea Butter, Vitamin E'
    },
    'weight-gain-powder': {
        id: 'weight-gain-powder',
        name: 'Weight Gain Powder',
        brand: 'DHERBALBODY SKINCARE',
        category: 'POWDER',
        price: 50.00,
        originalPrice: null,
        rating: 4.6,
        reviewCount: 89,
        images: [realProductImages[1]],
        inStock: true,
        isNew: false,
        onSale: false,
        isBestSeller: false,
        variants: ['#ffa500', '#ff8c00'],
        skinType: ['medium', 'dark'],
        unitCount: ['30ml'],
        features: ['Flawless finish', 'Long-lasting wear'],
        description: 'Trying to Gain some Weight is not as difficult as it seems. Our Weight Gain Powder does a wonderful job in increasing the fat levels in your estrogen making you gain a healthy weight. Comes in 1 kilo for a pack. You can mix it with your daily meals or as beverages. Super effective with early visible results. Price $50',
        ingredients: 'Aqua, Dimethicone, Titanium Dioxide, Iron Oxides, Vitamin C'
    },
    'bumcurve-essential-oil': {
        id: 'bumcurve-essential-oil',
        name: 'Bum Curve Essential Oil',
        brand: 'DHERBALBODY',
        category: 'BODY OIL',
        price: 45.00,
        originalPrice: 100.00,
        rating: 4.7,
        reviewCount: 203,
        images: [realProductImages[2]],
        inStock: true,
        isNew: true,
        onSale: true,
        isBestSeller: false,
        variants: ['#4169e1', '#6495ed'],
        skinType: ['sensitive', 'fair'],
        unitCount: ['60ml'],
        features: ['Birch butter formula', 'Silky smooth texture'],
        description: 'The Bumcurve Essential Oil was made to support & enhance growth of the "Buttocks" when applied. Produced with the finest natural organic oils & sourced out ingredients from all around the globe. The ingredients used initially will soak with the oils & with time it becomes more effective as you use. Visible Results within 2-3weeks✅. Price $45',
        ingredients: 'Aqua, Betula Alba Extract, Shea Butter, Glycerin, Allantoin'
    },
    'curves-n-butt-powder': {
        id: 'curves-n-butt-powder',
        name: 'CURVES AND BUTT POWDER',
        brand: 'DHERBALBODY SKINCARE',
        category: 'PROTEIN POWDER',
        price: 50.00,
        originalPrice: null,
        rating: 4.5,
        reviewCount: 134,
        images: [realProductImages[3]],
        inStock: true,
        isNew: false,
        onSale: false,
        isBestSeller: false,
        variants: ['#deb887', '#f5deb3'],
        skinType: ['light', 'medium'],
        unitCount: ['40ml'],
        features: ['Cedar extract formula', 'Renewal properties'],
        description: 'Curve & Butt Powder: This Product is made of essential food grinded in a powder form to give you the nutrients suitable for your Curves & Butt enhancement journey. It tastes good & can be used with your cereal, mixed in your daily meals or in your dessert such as yogurt. Very effective & results from 14 days of good use.',
        ingredients: 'Aqua, Cedarwood Oil, Glycerin, Panthenol, Tocopherol'
    },
    'omega-combo-max': {
        id: 'omega-combo-max',
        name: 'OMEGA COMBO MAX',
        brand: 'DHERBALBODY NATURALS',
        category: 'FACE CREAM',
        price: 150.00,
        originalPrice: null,
        rating: 4.9,
        reviewCount: 267,
        images: [realProductImages[4], '../images/additional_images/Combo-Max2.jpg'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#ff69b4', '#ffc0cb'],
        skinType: ['all'],
        unitCount: ['20ml'],
        features: ['Natural ingredients', 'Suitable for all skin types'],
        description: 'Omega Combo Set is the combination of both external & internal products together mainly targeted on people with stubborn estrogen levels to work effectively with visible results from 14 days +. This Combo at the same time is more affordable if purchased as a whole than buying the single products itself. It\'s a strong combination. Price $99',
        ingredients: 'Aqua, Aloe Vera, Jojoba Oil, Glycerin, Vitamin E'
    },
    'big-butt-formula': {
        id: 'big-butt-formula',
        name: 'Big Butt Formula (BBF) Herbal Organic Cream',
        brand: 'DHERBALBODY SKINCARE',
        category: 'BODY CREAM',
        price: 60.00,
        originalPrice: null,
        rating: 4.8,
        reviewCount: 0,
        images: [realProductImages[5], '../images/additional_images/BigButt2.jpg'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#f4a460', '#deb887'],
        skinType: ['all'],
        unitCount: ['50ml'],
        features: ['Handmade', 'Enhances butt & curves', 'Reduces stretch marks'],
        description: 'The Big Butt Formula (BBF) Herbal Organic cream is a wonderful handmade mixture of different nature filled ingredients that helps in enhancing the Butt & Curves areas. Tested & trusted by many customers that have used the products in recent times even gave testimonials on how it got rid of stretch marks along the journey of its effectiveness. We started our beauty business firstly with producing this fantastic product & now it\'s a buyers choice today💯✅. Price $60',
        ingredients: 'Herbal extracts, natural oils, shea butter, essential vitamins'
    },
    'big-maxi-capsule': {
        id: 'big-maxi-capsule',
        name: 'The Big Maxi Capsule',
        brand: 'DHERBALBODY NATURALS',
        category: 'SUPPLEMENT',
        price: 75.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: ['../images/additional_images/Butt XL Capsule.png'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#ff69b4'],
        skinType: ['all'],
        unitCount: ['60 capsules'],
        features: ['100% natural organic ingredients', 'Supports hormonal balance', 'Visible results from 14 days+'],
        description: 'This product was manufactured with the aim to help speed up the process of getting a more renounced result from your natural "Butt Enhancement" journey package. Tested & Trusted with many good positive & visible testimonials ✅💯🍑. It literally works from the inside waking up sleeping hormones that helps to enhance the Butt & Curves all together. It has been proven to help balance hormonal imbalance in women helping them with regular circles too. With a try you will tell the difference which is clear. Product is made up of 100% natural organic ingredients no additives or whatsoever. Results from 14days + .',
        ingredients: '100% natural organic ingredients'
    },
    'milk-lotion-triple-serum': {
        id: 'milk-lotion-triple-serum',
        name: 'Milk Lotion & Triple Action Serum',
        brand: 'DHERBALBODY SKINCARE',
        category: 'LOTION & SERUM',
        price: 75.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: [realProductImages[6], '../images/additional_images/Milk-2.jpg'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#fffacd', '#fff8dc'],
        skinType: ['light'],
        unitCount: ['100ml'],
        features: ['Brightens skin', 'Evens tone', 'Sunscreen protection', 'Multiple effects with serum'],
        description: 'Milk Lotion & Triple Action Serum : Specifically made for people naturally born with light skin. It helps to raise the dead skin & brighten it given it an even tone from head to toes. Comes with a sunscreen protector when used & under the sun to prevent "sun burns". You get ( × 2 ) multiple effects when mixed & used with the (Triple Action Serum).',
        ingredients: 'Milk proteins, sunscreen agents, brightening complex, Triple Action Serum'
    },
    'infection-herbs': {
        id: 'infection-herbs',
        name: 'Infection Herbs',
        brand: 'DHERBALBODY NATURALS',
        category: 'HERBAL REMEDY',
        price: 10.00,
        originalPrice: null,
        rating: 4.6,
        reviewCount: 0,
        images: ['#8B4513'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#8B4513'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Natural herbal blend', 'Anti-infection formula'],
        description: 'Natural herbal blend formulated to support the body\'s natural defense against infections. Made with carefully selected medicinal herbs known for their protective properties.',
        ingredients: 'Natural herbal extracts, traditional medicinal plants'
    },
    'fertility-package-wife': {
        id: 'fertility-package-wife',
        name: 'Fertility Package for Wife',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS PACKAGE',
        price: 10.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: ['#228B22'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#228B22'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Designed for women', 'Fertility support', 'Natural ingredients'],
        description: 'Specially designed fertility support package for women. Combines traditional herbal wisdom with modern wellness approaches to promote reproductive health and balance.',
        ingredients: 'Natural fertility herbs, plant-based nutrients'
    },
    'major-fertility-couples': {
        id: 'major-fertility-couples',
        name: 'Major Fertility Package for Couples',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS PACKAGE',
        price: 10.00,
        originalPrice: null,
        rating: 4.8,
        reviewCount: 0,
        images: ['#6B4423'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#6B4423'],
        skinType: ['all'],
        unitCount: [''],
        features: ['For couples', 'Comprehensive fertility support', 'Natural formula'],
        description: 'Comprehensive fertility support package designed for couples seeking to enhance reproductive wellness. A complete natural solution for both partners on their fertility journey.',
        ingredients: 'Premium herbal blend, balanced fertility herbs'
    },
    'manhood-failure': {
        id: 'manhood-failure',
        name: 'Manhood Failure Support',
        brand: 'DHERBALBODY NATURALS',
        category: 'HERBAL REMEDY',
        price: 10.00,
        originalPrice: null,
        rating: 4.5,
        reviewCount: 0,
        images: ['#8B6914'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#8B6914'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Natural support', 'Traditional formula', 'Wellness oriented'],
        description: 'Natural herbal formula designed to support masculine vitality and wellness. Combines time-honored herbal ingredients known for their revitalizing properties.',
        ingredients: 'Natural masculine support herbs, plant-based vitality blend'
    },
    'hormonal-imbalance': {
        id: 'hormonal-imbalance',
        name: 'Hormonal Imbalance Support',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS SUPPORT',
        price: 10.00,
        originalPrice: null,
        rating: 4.6,
        reviewCount: 0,
        images: ['#2D5016'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#2D5016'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Hormonal balance', 'Natural herbs', 'Holistic approach'],
        description: 'Herbal formula specifically crafted to support hormonal balance and equilibrium. Uses natural ingredients traditionally used to regulate and harmonize hormonal levels.',
        ingredients: 'Balancing herbal extracts, hormone support plants'
    },
    'high-prolactin': {
        id: 'high-prolactin',
        name: 'High Prolactin Treatment',
        brand: 'DHERBALBODY NATURALS',
        category: 'HERBAL REMEDY',
        price: 10.00,
        originalPrice: null,
        rating: 4.5,
        reviewCount: 0,
        images: ['#556B2F'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#556B2F'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Natural remedy', 'Prolactin regulation', 'Herbal support'],
        description: 'Natural herbal support designed to help regulate prolactin levels. Made with carefully selected medicinal plants traditionally used for hormonal balance.',
        ingredients: 'Prolactin-balancing herbs, natural remedial plants'
    },
    'pussysweetener-aphrodisiac': {
        id: 'pussysweetener-aphrodisiac',
        name: 'Pussysweetener & Aphrodisiac',
        brand: 'DHERBALBODY NATURALS',
        category: 'INTIMATE WELLNESS',
        price: 10.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: ['#A0522D'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#A0522D'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Aphrodisiac blend', 'Intimate wellness', 'Natural formula'],
        description: 'Intimate wellness formula combining traditional aphrodisiac herbs. Designed to enhance natural vitality and support intimate wellness through natural herbal ingredients.',
        ingredients: 'Aphrodisiac herbs, natural intimacy support blend'
    },
    'big-manhood-soap': {
        id: 'big-manhood-soap',
        name: 'Big Manhood Soap',
        brand: 'DHERBALBODY NATURALS',
        category: 'HERBAL SOAP',
        price: 10.00,
        originalPrice: null,
        rating: 4.6,
        reviewCount: 0,
        images: ['#8B7355'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#8B7355'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Herbal soap', 'Natural cleansing', 'Wellness support'],
        description: 'Herbal-infused natural soap formulated with ingredients traditionally used for masculine wellness. Gentle cleansing with natural support properties.',
        ingredients: 'Natural herbal soap base, masculine support herbs'
    },
    'pcos-support': {
        id: 'pcos-support',
        name: 'PCOS Support',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS SUPPORT',
        price: 10.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: ['#3D5A3D'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#3D5A3D'],
        skinType: ['all'],
        unitCount: [''],
        features: ['PCOS support', 'Hormonal wellness', 'Natural herbs'],
        description: 'Comprehensive herbal support formula designed for those managing PCOS. Combines traditional herbs known to support natural hormonal balance and wellness.',
        ingredients: 'PCOS-support herbs, hormone-balancing plant extracts'
    },
    'progesterone-kit': {
        id: 'progesterone-kit',
        name: 'Progesterone Kit',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS KIT',
        price: 10.00,
        originalPrice: null,
        rating: 4.8,
        reviewCount: 0,
        images: ['#704214'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#704214'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Progesterone support', 'Complete kit', 'Natural formula'],
        description: 'Complete natural support kit specially formulated to promote healthy progesterone levels. Includes carefully selected herbs traditionally used for hormonal wellness.',
        ingredients: 'Progesterone-supporting herbs, natural hormonal balance blend'
    },
    'low-sperm-count': {
        id: 'low-sperm-count',
        name: 'Low Sperm Count Treatment',
        brand: 'DHERBALBODY NATURALS',
        category: 'HERBAL REMEDY',
        price: 10.00,
        originalPrice: null,
        rating: 4.6,
        reviewCount: 0,
        images: ['#696969'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#696969'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Male fertility support', 'Natural formula', 'Herbal blend'],
        description: 'Natural herbal formula designed to support male fertility and sperm health. Made with nutrient-rich herbs traditionally used to enhance male reproductive wellness.',
        ingredients: 'Fertility-enhancing herbs, male wellness plant extracts'
    },
    'ovarian-cyst-support': {
        id: 'ovarian-cyst-support',
        name: 'Ovarian Cyst Support',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS SUPPORT',
        price: 10.00,
        originalPrice: null,
        rating: 4.5,
        reviewCount: 0,
        images: ['#2F4F2F'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#2F4F2F'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Cyst support', 'Natural remedy', 'Women wellness'],
        description: 'Natural herbal support specifically designed for women managing ovarian cysts. Formulated with traditional herbs known for their supportive properties.',
        ingredients: 'Ovarian wellness herbs, natural support plant blend'
    },
    'endometriosis-support': {
        id: 'endometriosis-support',
        name: 'Endometriosis Support',
        brand: 'DHERBALBODY NATURALS',
        category: 'WELLNESS SUPPORT',
        price: 10.00,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 0,
        images: ['#654321'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: false,
        variants: ['#654321'],
        skinType: ['all'],
        unitCount: [''],
        features: ['Endometriosis support', 'Natural herbs', 'Wellness formula'],
        description: 'Comprehensive herbal support formula for those managing endometriosis. Combines natural ingredients traditionally used to support women\'s health and wellness.',
        ingredients: 'Endometriosis-support herbs, pain-relief plant extracts'
    },
    'super-boobs-combo-set': {
        id: 'super-boobs-combo-set',
        name: 'Super Boobs Combo Set',
        brand: 'DHERBALBODY NATURALS',
        category: 'COMBO SET',
        price: 120.00,
        originalPrice: null,
        rating: 4.9,
        reviewCount: 0,
        images: ['../images/additional_images/Boobs_Booster.png'],
        inStock: true,
        isNew: true,
        onSale: false,
        isBestSeller: true,
        variants: ['#ff69b4', '#ffc0cb'],
        skinType: ['all'],
        unitCount: ['3-piece combo'],
        features: ['Boobs Firming Oil (100g)', 'Capsules (60 counts)', 'Powder (300-500g)', 'Complete boost & firm system', 'Addresses internal & external enhancement'],
        description: 'Super Boobs Combo Set: In this package we carefully have combined 3 solid natural products to help "Boost & Firm" your melons raising them to live on a 100%. We started off with the Boobs Booster essential oils which sold out in 2021 in its first 3 months with unbelievable testimonials from customers around the globe. When Dherbalbody discovered how stubborn "estrogen" levels are in some women we did our research and finally added the Capsules + the Powder mix to deal with the internal growing process. Today we are proud to sell this effective combo with pride to give you a full confidence ✅🌝. Package includes: Boobs Firming Oil (100g), Capsules (60 counts), Powder (300-500g). Price $120',
        ingredients: 'Boobs Booster essential oils, natural estrogen-supporting herbs, capsule blend, powder mix with organic nutrients'
    }
};

export function getProduct(productId) {
    return productsData[productId] || null;
}

export function formatPrice(price) {
    return `$${price.toFixed(2)}`;
}

export function generateStarRating(rating) {
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 >= 0.5;
    const emptyStars = 5 - fullStars - (hasHalfStar ? 1 : 0);
    let starsHtml = '';
    for (let i = 0; i < fullStars; i++) {
        starsHtml += `<span class='star'>★</span>`;
    }
    if (hasHalfStar) {
        starsHtml += `<span class='star'>☆</span>`;
    }
    for (let i = 0; i < emptyStars; i++) {
        starsHtml += `<span class='star'>☆</span>`;
    }
    return starsHtml;
}
